### ISSUE TITLE
Backend - Generate pre-computed skills files

### ISSUE THREAD

**Issue by emily-bicks** [nestauk/dap_ds_mcc_job_similarity_tool#3]
- design data schema
- refactor code to output the data
- incorporate crosswalk of occupations that Sussex is interested in

**Comment by emily-bicks** [comment]
Additional things we need in the output file:
- work contexts / zones that match
- industry of the job so we can filter to the high priority industries
- more than just the top 3 so that if we filter to high priority industries we can still display 3 matches

**Comment by emily-bicks** [comment]
Additional things we need in the output file:
- work contexts / zones that match
- industry of the job so we can filter to the high priority industries
- more than just the top 3 so that if we filter to high priority industries we can still display 3 matches

**Comment by emily-bicks** [comment]
- sometimes the current job shows up as the highest match for the next job (ex: mathematics teacher at secondary school)

**Comment by emily-bicks** [comment]
- the "missing skills" seem to be skills from the current job, not from the job we're recommending

**Comment by EnricoGavagnin** [comment]
I created dedicated issues for those still open and linked them to the backend milestone
